language: node_js
sudo: false
node_js:
- '14'
install:
- yarn
cache:
  timeout: 3600
  yarn: true
  directories:
  - node_modules
  - projects/ngx-openlayers/node_modules
  - dist

jobs:
  include:
  - stage: check
    name: next lib linting
    script:
    - yarn lint

  - stage: build
    name: next lib and demo
    script:
    - yarn build:lib
    - cp -r dist/ngx-openlayers dist/ngx-openlayers-publish
    - yarn build:demo --base-href "/ngx-openlayers/"  --progress false

  - stage: release
    name: next lib version on github releases
    if: tag =~ /^\d+.\d+.\d+-next.\d+$/
    script: 'true' # skips tests
    before_deploy:
    - cd dist/ngx-openlayers-publish
    - cp ../../projects/ngx-openlayers/CHANGELOG.md CHANGELOG.md
    - npm pack
    deploy:
    - provider: releases
      prerelease: true
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: '*.tgz'
      skip_cleanup: true
      on:
        tags: true

  - stage: release
    name: next demo on github pages
    if: tag =~ /^\d+.\d+.\d+-next.\d+$/
    script: 'true' # skips tests
    before_deploy:
    - cd dist/demo-ngx-openlayers
    deploy:
    - provider: pages
      local_dir: dist/demo-ngx-openlayers
      skip_cleanup: true
      github_token: $GITHUB_OAUTH_TOKEN
      on:
        tags: true

  - stage: deploy
    name: next lib version on npm
    if: tag =~ /^\d+.\d+.\d+-next.\d+$/
    script: 'true' # skips tests
    before_deploy:
    - cp projects/ngx-openlayers/CHANGELOG.md dist/ngx-openlayers-publish/CHANGELOG.md
    - cd dist/ngx-openlayers-publish
    deploy:
    - provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      tag: next
      skip_cleanup: true
      on:
        tags: true
